options(repos = c(CRAN = "https://cloud.r-project.org"))
if (!require("remotes", quietly = TRUE)) install.packages("remotes")
remotes::install_url("https://laquali-ufla.github.io/maRS/maRS_inst_pkg.zip", force = TRUE, upgrade = "always")
library(maRS)
maRS::create_shortcuts(force = TRUE)